*** TRUNCATION FUNCTIONS ***;
DATA TRUNCATION_FUNCTION;
	ceil_ = CEIL(11.85);
	floor_ = FLOOR(11.85);
	int_ = INT(11.85);
	round_ = ROUND(561.78);
RUN;
	
PROC PRINT DATA = TRUNCATION_FUNCTION NOOBS;
RUN;